CREATE TABLE [dbo].[Account] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [RoleId]            INT            NOT NULL,
    [Name]              VARCHAR (250)  NOT NULL,
    [Email]             NVARCHAR (250) NOT NULL,
    [Password]          NVARCHAR (50)  NOT NULL,
    [CompanyName]       NVARCHAR (500) NULL,
    [ContactNumber]     NVARCHAR (500) NULL,
    [Address]           NVARCHAR (MAX) NULL,
    [StreetAddress]     NVARCHAR (MAX) NULL,
    [ZipCode]           NVARCHAR (MAX) NULL,
    [ProductCategoryId] INT            NOT NULL,
    [IsGstAvailable]    NVARCHAR (50)  NULL,
    [GstNumber]         NVARCHAR (MAX) NULL,
    [AccountNumber]     NVARCHAR (MAX) NULL,
    [AccountHolderName] NVARCHAR (MAX) NULL,
    [IfscCode]          NVARCHAR (MAX) NULL,
    [IsNumberVerified]  BIT            NULL,
    [IsDeleted]         BIT            NOT NULL,
    [IsActive]          BIT            NOT NULL,
    [IsAccountVerified] BIT            NOT NULL,
    [Image]             NVARCHAR (MAX) NULL,
	IdProofPath             NVARCHAR (MAX) NULL,
	CancelledChequePath             NVARCHAR (MAX) NULL,
    [CreatedDt]         DATETIME       NOT NULL,
    [ModifiedBy]        INT            NULL,
    [ModifiedDt]        DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

